name: Ingress Readiness
description: Validates URL availability
inputs:
  endpoints:
    description: List of space separated URLs to verify
    required: true
  timeout:
    description: Number of seconds for all endpoints to come alive
    default: 120
runs:
  using: composite
  steps:
    - name: Check readiness
      shell: bash
      env:
        ENDPOINTS: ${{ inputs.endpoints }}
        TIMEOUT: ${{ inputs.timeout }}
      run: |
        time_elapsed=0

        for endpoint in ${ENDPOINTS}; do
          until $(curl -o /dev/null -q -s -m 2 --fail --head -H "Host: $endpoint" http://127.0.0.1); do
            if [ ${time_elapsed} -ge ${TIMEOUT} ]; then
              echo "Timeout waiting for readiness"
              kubectl get all -n echo
              exit 1
            fi

            sleep 5 
            time_elapsed=$((time_elapsed+5))
            echo -n "."
          done
        done

