name: CI Load Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Kubernetes setup
        uses: helm/kind-action@v1
        with:
          config: cluster-setup/kind-config.yml

      - name: Kubernetes check
        shell: bash
        run: |
          kubectl get nodes -o wide

      - name: Nginx controller install
        uses: ./.github/actions/helm-install
        with:
          name: nginx
          repository: nginx
          repository-url: https://kubernetes.github.io/ingress-nginx
          chart: ingress-nginx
          namespace: ingress
          values-file: cluster-setup/deploy/system/nginx-controller/values.yaml

      - name: Nginx check
        shell: bash
        run: |
          netstat -ntlp
          curl -o - http://127.0.0.1/

      - name: Foo install
        uses: ./.github/actions/helm-install
        with:
          name: foo
          chart: cluster-setup/charts/http-echo
          namespace: echo
          values-file: cluster-setup/deploy/app/foo/values.yaml

      - name: Bar install
        uses: ./.github/actions/helm-install
        with:
          name: bar
          chart: cluster-setup/charts/http-echo
          namespace: echo
          values-file: cluster-setup/deploy/app/bar/values.yaml


      - name: App check
        shell: bash
        run: |
          echo "Foo:"
          curl -o - -H "Host: foo.local" -d "hello=foo" http://127.0.0.1
          echo ""
          echo "Bar:"
          curl -o - -H "Host: bar.local" -d "hello=bar" http://127.0.0.1



