name: CI Load Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Kubernetes setup
        uses: helm/kind-action@v1
        with:
          config: cluster-setup/kind-config.yml

      - name: Kubernetes check
        shell: bash
        run: |
          kubectl get nodes -o wide

      - name: Nginx controller install
        uses: ./.github/actions/helm-install
        with:
          name: nginx
          repository: nginx
          repository-url: https://kubernetes.github.io/ingress-nginx
          chart: ingress-nginx
          namespace: ingress
          values-file: cluster-setup/deploy/system/nginx-controller/values.yaml


      - name: Nginx check
        shell: bash
        run: |
          netstat -ntlp
          curl -o - http://127.0.0.1/
